
name: Bootcamp Sample2
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          version:  12
    
      - name: GitHub Action for Yarn

        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
          
      - name : creating build
      - name: yarn build
        
      - name : installing surge
        run : npm install -g surge
     
      - name : deploying on surge
        run : surge ./build http://bootcamp_sample2.surge.sh/ --token ${{secrets.SURGE_TOKEN}}

